ovirt-engine:
  build: ./$MAJOR_VERSION
  environment:
    - OVIRT_PASSWORD=engine
    - POSTGRES_DB=engine
    - POSTGRES_HOST=postgres
    - HOST_ENCRYPT=false
    - HOST_INSTALL=false
  links:
    - postgres
  ports:
    - 8443:8443
    - 8787:8787

postgres:
  image: rmohr/ovirt-postgres
  environment:
    - POSTGRES_PASSWORD=engine
    - POSTGRES_USER=engine
    - POSTGRES_DB=engine
  ports:
    - 5432:5432
